### ISSUE TITLE
user & mail enumeration via registration

### ISSUE THREAD

**Issue by mkind** [liqd/adhocracy3.mercator#606]
It is possible to iterate over usernames and email addresses via `POST http://localhost:6541/principals/users/` call. This is because the backend's response contains the precise information `The user login name is not unique` or `The user login email is not unique`. As a consequence, one is able to gather information about valid login names.

**Ideas:**
* use captchas
* use mail address as unique login names
* do not inform the user whether mail address is already used

**Comment by ChristianSi** [comment]
"Enumeration" is certainly not possible since users have to know the name oder email in order to check whether it exists already.

Also, user names are public anyway, we don't try to hide them.

For emails it's true that POSTing a new user user account with a specific email address allows finding out whether that email already belongs to an account. We cannot accept the same address for multiple accounts so I don't really see how we can avoid that. I also think that most other websites/platforms will have the same "leak" so I don't see it as a grave problem.

**Comment by mkind** [comment]
Usually it is not critical having public user names, but as soon as the names become part of the authentication/login process it's getting ugly. Its trivial to get all existing user names, which makes it appealing to brute force their passwords.

**Comment by ChristianSi** [comment]
We could require login per email address instead of user name but that would affect usability, and it doesn't solve the basic problem -- if people have somebody's email address, they could still try to brute-force their account. I guess the most sensible solution is to limit failed login attempts (wait a few seconds before we respond in such cases, possibly block the iP after repeated attempts). In Adhocracy 2, it apparently was never necessary to deploy such a solution, so I guess we can start A3 without it too and add it later, if needed.

It's definitely something we should keep in mind.
