### ISSUE TITLE
Strange sorting in proposal list

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#627]
When I support/unsupport a proposal, the proposal list is resorted. But I do not understand the algorithm by which it is sorted. Further investigation required.

**Comment by MagdaN** [comment]
When support button is clicked somehow - maybe because of some websocket - the list sends an request to update itself, but, I guess, as nothing is changed gets the data from cache, which has already been sorted but gets sorted again (by that I mean 'elements.reverse()' ) and so the sorting gets reversed.

**Comment by nidico** [comment]
Note that this is only partially solved as #714 is still open.
